### PR TITLE
Branch git week1

### PR DESCRIPTION
**Pull request by yuvi20188**

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
Hi Iuliia, i'm sorry to say but your homework is not correct :(
For exercise 1, you should add the .gitignore file on the branch `main`  on your computer and then push to github.
For exercise 2, the instructions say to add/commit one file at a time, and you added/committed the 3 files at once.
So, I'm going to ask you to do your homework again. But before you start again, please close this Pull Request.
If something is not clear or you need help with anything, just say on slack :)

**Comment by miltonhultgren** [comment]
@marta-ov We worked together to update `main` and this branch to match the homework requirements :)

**Comment by marta-ov** [comment]
This is great @yuvi20188! Thank you for the help @miltonhultgren :D

You can merge the PR @yuvi20188 :)

**Comment by yuvi20188** [comment]
Thank you

пт, 28 окт. 2022 г., 14:37 marta-ov ***@***.***>:

**Pull request merged**
